### PR TITLE
Fixes

### LINKED ISSUE #3: add support to run on windows
Hi, I am new to cerebral, but what I have read about it is amazing. So, I wanted to try it out, using the cli. But, when doing so it didn't work out:

```
C:\src>npm install cerebral-cli

> spawn-sync@1.0.15 postinstall C:\src\node_modules\spawn-sync
> node postinstall

C:\src
`-- cerebral-cli@0.0.10
  +-- fs-extra@0.27.0
  | +-- graceful-fs@4.1.4
  | +-- jsonfile@2.3.1
  | +-- klaw@1.3.0
  | +-- path-is-absolute@1.0.0
  | `-- rimraf@2.5.3
  |   `-- glob@7.0.5
  |     +-- fs.realpath@1.0.0
  |     +-- inflight@1.0.5
  |     | `-- wrappy@1.0.2
  |     +-- inherits@2.0.1
  |     +-- minimatch@3.0.2
  |     | `-- brace-expansion@1.1.5
  |     |   +-- balanced-match@0.4.1
  |     |   `-- concat-map@0.0.1
  |     `-- once@1.3.3
  +-- inquirer@1.1.2
  | +-- ansi-escapes@1.4.0
  | +-- chalk@1.1.3
  | | +-- ansi-styles@2.2.1
  | | +-- escape-string-regexp@1.0.5
  | | +-- has-ansi@2.0.0
  | | `-- supports-color@2.0.0
  | +-- cli-cursor@1.0.2
  | | `-- restore-cursor@1.0.1
  | |   +-- exit-hook@1.1.1
  | |   `-- onetime@1.1.0
  | +-- cli-width@2.1.0
  | +-- external-editor@1.0.3
  | | +-- extend@3.0.0
  | | +-- spawn-sync@1.0.15
  | | | +-- concat-stream@1.5.1
  | | | | +-- readable-stream@2.0.6
  | | | | | +-- core-util-is@1.0.2
  | | | | | +-- isarray@1.0.0
  | | | | | +-- process-nextick-args@1.0.7
  | | | | | +-- string_decoder@0.10.31
  | | | | | `-- util-deprecate@1.0.2
  | | | | `-- typedarray@0.0.6
  | | | `-- os-shim@0.1.3
  | | `-- temp@0.8.3
  | |   +-- os-tmpdir@1.0.1
  | |   `-- rimraf@2.2.8
  | +-- figures@1.7.0
  | | `-- object-assign@4.1.0
  | +-- lodash@4.13.1
  | +-- mute-stream@0.0.6
  | +-- pinkie-promise@2.0.1
  | | `-- pinkie@2.0.4
  | +-- run-async@2.2.0
  | | `-- is-promise@2.1.0
  | +-- rx@4.1.0
  | +-- string-width@1.0.1
  | | +-- code-point-at@1.0.0
  | | | `-- number-is-nan@1.0.0
  | | `-- is-fullwidth-code-point@1.0.0
  | +-- strip-ansi@3.0.1
  | | `-- ansi-regex@2.0.0
  | `-- through@2.3.8
  `-- yargs@4.8.0
    +-- cliui@3.2.0
    | `-- wrap-ansi@2.0.0
    +-- decamelize@1.2.0
    +-- lodash.assign@4.0.9
    | +-- lodash.keys@4.0.7
    | `-- lodash.rest@4.0.3
    +-- os-locale@1.4.0
    | `-- lcid@1.0.0
    |   `-- invert-kv@1.0.0
    +-- read-pkg-up@1.0.1
    | +-- find-up@1.1.2
    | | `-- path-exists@2.1.0
    | `-- read-pkg@1.1.0
    |   +-- load-json-file@1.1.0
    |   | +-- parse-json@2.2.0
    |   | | `-- error-ex@1.3.0
    |   | |   `-- is-arrayish@0.2.1
    |   | +-- pify@2.3.0
    |   | `-- strip-bom@2.0.0
    |   |   `-- is-utf8@0.2.1
    |   +-- normalize-package-data@2.3.5
    |   | +-- hosted-git-info@2.1.5
    |   | +-- is-builtin-module@1.0.0
    |   | | `-- builtin-modules@1.1.1
    |   | +-- semver@5.2.0
    |   | `-- validate-npm-package-license@3.0.1
    |   |   +-- spdx-correct@1.0.2
    |   |   | `-- spdx-license-ids@1.2.1
    |   |   `-- spdx-expression-parse@1.0.2
    |   |     `-- spdx-exceptions@1.0.4
    |   `-- path-type@1.1.0
    +-- require-directory@2.1.1
    +-- require-main-filename@1.0.1
    +-- set-blocking@2.0.0
    +-- which-module@1.0.0
    +-- window-size@0.2.0
    +-- y18n@3.2.1
    `-- yargs-parser@2.4.0
      `-- camelcase@2.1.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\src\package.json'
npm WARN src No description
npm WARN src No repository field.
npm WARN src No README data
npm WARN src No license field.

C:\src>cerebral new cerebral
'cerebral' is not recognized as an internal or external command,
operable program or batch file.
```

### LINKED ISSUE #5: suggestions
- [x] remove decorators legacy stuff
- [ ] allow to have empty view choise
- [x] use new models exposed at `cerebral/models`

### PR DESCRIPTION
**Pull request by Guria**
fix #5 
fix #3

### CODE REVIEW

**Comment by christianalfoni** [comment]
This looks awesome! Does this also npm install correctly on windows?

**Comment by Guria** [comment]
yes

**Comment by bfitch** [comment]
@Guria Feel free to ignore, but was wondering: is there a cross-platform way to log the scaffolded directory? Was doing `stdout = exec(`find ${appName} -type d -print`, {stdio: [0]})` before.

Merge it in! 🚀

**Comment by Guria** [comment]
@bfitch I haven't explored yet. I am on mobile atm. You can merge and release it.

**Pull request merged**
